// <auto-generated />
using System;
using EPM.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EPM.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230202014042_InitDbSeed")]
    partial class InitDbSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EPM.API.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfUsers")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("clients");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ClientName = "AdaptIT_JHB",
                            CreatedOn = new DateTime(2023, 2, 1, 17, 40, 42, 353, DateTimeKind.Local).AddTicks(3430),
                            Location = "Gauteng",
                            NumberOfUsers = 8
                        },
                        new
                        {
                            ID = 2,
                            ClientName = "AdaptIT_CA",
                            CreatedOn = new DateTime(2023, 2, 1, 17, 40, 42, 356, DateTimeKind.Local).AddTicks(8177),
                            Location = "Eastern Cape",
                            NumberOfUsers = 1
                        },
                        new
                        {
                            ID = 3,
                            ClientName = "AdaptIT_KZN",
                            CreatedOn = new DateTime(2023, 2, 1, 17, 40, 42, 356, DateTimeKind.Local).AddTicks(8564),
                            Location = "Durban",
                            NumberOfUsers = 4
                        },
                        new
                        {
                            ID = 4,
                            ClientName = "TG-Tech",
                            CreatedOn = new DateTime(2023, 2, 1, 17, 40, 42, 356, DateTimeKind.Local).AddTicks(8622),
                            Location = "Gauteng",
                            NumberOfUsers = 9
                        });
                });

            modelBuilder.Entity("EPM.API.Models.Users", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "Biologicaltk@gmail.com",
                            Password = "Pass1",
                            Role = "Admin",
                            Username = "Tshoki"
                        },
                        new
                        {
                            ID = 2,
                            Email = "gao@gmail.com",
                            Password = "Pass2",
                            Role = "Admin",
                            Username = "Gao"
                        },
                        new
                        {
                            ID = 3,
                            Email = "titik@yahoo.com",
                            Password = "Pass3",
                            Role = "User",
                            Username = "Titi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
